name: ESPHome

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  config:
    name: Config against ESPHome dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install ESPHome
        run: pip install "esphome @ git+https://github.com/esphome/esphome.git@dev"
      - name: Validate configs
        run: ./tests/ci
      - name: Host connection
        run: ./tests/host-run

  compile:
    name: Compile against ESPHome dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install ESPHome
        run: pip install "esphome @ git+https://github.com/esphome/esphome.git@dev"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache
            ~/.espressif
          key: esphome-dev-${{ runner.os }}
      - name: Compile
        run: esphome compile tests/compile.yaml
